[project]
name = "isimip-utils"
authors = [
    { name = "Jochen Klar", email = "jochen.klar@pik-potsdam.de" },
]
maintainers = [
    { name = "Jochen Klar", email = "jochen.klar@pik-potsdam.de" },
]
description = "This package contains common functionality for different ISIMIP tools."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
classifiers = [
    'Operating System :: OS Independent',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
dependencies = [
    "colorlog",
    "netCDF4",
    "python-dotenv",
    "requests"
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/ISI-MIP/isimip-utils"

[tool.setuptools]
packages = ["isimip_utils"]

[tool.setuptools.dynamic]
version = { attr = "isimip_utils.__version__" }
